### ISSUE TITLE
website_sale_add_to_cart_disable module doesn't hide button

### ISSUE THREAD

**Issue by osadmn** [itpp-labs/website-addons#172]
Hi @yelizariev , 

I installed the website_sale_add_to_cart_disable module (v8) and didn't get it to work. Then I tried it in the runbot (http://runbot.it-projects.info/demo/website-addons/8.0) and there it doesn't work either. This is if I understand correctly what it's supposed to do ... it removes the "Add to cart" button from a product page in the website when the "Show Add To Cart button" property of the product template isn't checked, right?

Thanks,
Els

**Comment by yelizariev** [comment]
I tried to install only website_sale_add_to_cart_disable and it works.
The module could be incompatible with another module
![screenshot-04149-8-0-a41a17-base runbot it-projects info 2017-03-24 15-17-52](https://cloud.githubusercontent.com/assets/186131/24289966/1856a354-10a5-11e7-9b2f-1171b11fb66c.png)

**Comment by mhdsyarif** [comment]
It same error, I installed the website_sale_add_to_cart_disable module (v10) and didn't get it to work.
source : [https://www.odoo.com/apps/modules/10.0/website_sale_add_to_cart_disable/](https://www.odoo.com/apps/modules/10.0/website_sale_add_to_cart_disable/)
![selection_465](https://user-images.githubusercontent.com/5978109/33984468-4b80f4da-e0ea-11e7-83c8-5ffcd777607a.png)

Thanks,
Syarif

**Comment by Ark74** [comment]
Maybe not the best approach, but once you add
https://www.odoo.com/apps/modules/10.0/website_sale_add_to_cart/

Then the **Add to Cart** goes away. Check it out :smile:

**Comment by Highcooley** [comment]
Same problem here. The module does not hide the add to cart button in Odoo 10.0-20180122 community edition

**Comment by trojikman** [comment]
> Maybe not the best approach, but once you add
> https://www.odoo.com/apps/modules/10.0/website_sale_add_to_cart/
> 
> Then the **Add to Cart** goes away. Check it out

this is the purpose of the module

**Comment by trojikman** [comment]
I installed the module on 10.0, did everything according to the [instructions](https://github.com/itpp-labs/website-addons/blob/10.0/website_sale_add_to_cart_disable/doc/index.rst) and everything works. Probably, the description of the module does not obviously say that by default the `Add To Cart` button is active, it must be disabled for each product separately as stated in [documentation](https://github.com/itpp-labs/website-addons/blob/10.0/website_sale_add_to_cart_disable/doc/index.rst)
