### ISSUE TITLE
website_sale_checkout_store: unwanted redirect

### ISSUE THREAD

**Issue by trojikman** [itpp-labs/website-addons#337]
In cases when ship enabled(nobill_ship and bill_ship) if you disable checkbox on shop/address ("Ship to the same address" ) and post "Shipping address" you will be redirected to shop/address again

**Comment by ilmir-k** [comment]
@trojikman I need the odoo version you used for reproducing

**Comment by trojikman** [comment]
@ilmir-k 11.0

**Comment by trojikman** [comment]
this is funny but i can't reproduce the error

**Comment by yelizariev** [comment]
¯\_(ツ)_/¯

**Comment by trojikman** [comment]
![Farmer_meme](https://user-images.githubusercontent.com/23641186/75322243-2f49ef00-5894-11ea-8d91-eba8cf95d9e1.jpg)
