### ISSUE TITLE
[10.0]Stock barcode packages issue

### ISSUE THREAD

**Issue by flotho** [itpp-labs/website-addons#406]
Hi @ilmir-k , @yelizariev ,

Hope you're doing well.
We're running a 10.0 version and trying to use the barcode port you made.
Here is our issue : 
```
TypeError: myPackage.ul_id is undefined[En savoir plus] widgets.js:103:37 
```

The error is thrown there https://github.com/it-projects-llc/website-addons/blob/10.0/stock_picking_barcode/static/lib/widgets.js#L83 and only when trying to change from a picking to another one.

**Comment by trojikman** [comment]
Hi, thanks for your feedback! 
I have not seen such an error. It would be great to have more details and steps to reproduce it.
Feel free to reopen with more information.

Best regards
