### ISSUE TITLE
[website_debranding] upload image widget still shows odoo website

### ISSUE THREAD

**Issue by auyeung112002** [itpp-labs/website-addons#434]
![image](https://user-images.githubusercontent.com/8391358/61941912-f6c6f780-afca-11e9-82fc-f1c150b5aa54.png)

**Comment by trojikman** [comment]
Thanks for the report. Please specify the version of the Odoo in which you encounter this bug

**Comment by trojikman** [comment]
It is probably fixed in https://github.com/itpp-labs/misc-addons/pull/990
