### ISSUE TITLE
website_sale_auto_confirm_order

### ISSUE THREAD

**Issue by morphace** [itpp-labs/website-addons#5]
Hi,

I tried website_sale_auto_confirm_order and it works well, thanks!

One issue I have: the customer receives a confirmation email for the quote, not the sale order.
This is probably the case because the email is sent before the quote has been confirmed.
Is there any way to change this?

Thanks,
Markus

**Comment by yelizariev** [comment]
Hi,

I don't have quick answer for your question. I'd return to this issue when I'll have time

**Comment by trojikman** [comment]
Since the `website_sale_auto_confirm_order` module last appeared in branch 9.0 which we no longer support, I have no other choice but to close this issue
