### ISSUE TITLE
DINAR-PORT 12.0 website_sale_add_to_cart

### ISSUE THREAD

**Issue by yelizariev** [itpp-labs/website-addons#585]

**Comment by trojikman** [comment]
Надо бы как-то помечать модули которые не получилось портировать автоматически, чтобы не запускать автопорторование повторно

**Comment by yelizariev** [comment]
Не знаю как лучше. Можно поиск по закрытым делам\ПР искать, например
Этот модуль не очень нужен, поэтому я закрывал ПР
